# Generated by Django 4.0.6 on 2022-07-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinelearningmodel',
            name='version',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='MachineLearningModelVersion',
        ),
    ]
