# Generated by Django 4.0.6 on 2022-08-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0004_alter_machinelearningmodel_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinelearningmodel',
            name='name',
            field=models.CharField(default='Anonymous', max_length=2000),
        ),
    ]
