# Generated by Django 4.0.6 on 2022-08-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0005_alter_machinelearningmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinelearningmodel',
            name='name',
            field=models.CharField(max_length=2000, unique=True),
        ),
    ]
