# Generated by Django 4.0.6 on 2022-08-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0007_alter_machinelearningmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinelearningmodel',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='machinelearningmodel',
            name='state',
            field=models.CharField(choices=[('PR', 'processing'), ('ER', 'error'), ('CO', 'complete')], default='PR', max_length=2),
        ),
        migrations.AddField(
            model_name='machinelearningmodel',
            name='task_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
