# Generated by Django 4.0.7 on 2022-09-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0009_alter_machinelearningmodel_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinelearningmodel',
            old_name='url',
            new_name='mar_url',
        ),
        migrations.AddField(
            model_name='machinelearningmodel',
            name='mar_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
