# Generated by Django 4.0.7 on 2022-09-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0010_rename_url_machinelearningmodel_mar_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinelearningmodel',
            name='mar_file',
            field=models.FileField(null=True, upload_to='models'),
        ),
    ]
