# Generated by Django 4.0.7 on 2022-10-06 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0011_alter_machinelearningmodel_mar_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='machinelearningmodel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='machinelearningmodel',
            name='mar_file',
        ),
        migrations.RemoveField(
            model_name='machinelearningmodel',
            name='mar_url',
        ),
        migrations.RemoveField(
            model_name='machinelearningmodel',
            name='version',
        ),
    ]
