# Generated by Django 4.0.7 on 2022-09-13 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turkle', '0013_activeproject_activeuser_alter_batch_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='turkle.batch')),
                ('metadata', models.JSONField(default=dict, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('turkle.batch', models.Model),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='turkle.project')),
                ('metadata', models.JSONField(default=dict, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('turkle.project', models.Model),
        ),
    ]
