# Generated by Django 4.0.7 on 2022-09-27 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turkle', '0013_activeproject_activeuser_alter_batch_id_and_more'),
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Batch',
            new_name='AnnotationBatch',
        ),
        migrations.RenameModel(
            old_name='Project',
            new_name='AnnotationProject',
        ),
    ]
