# Generated by Django 3.1.14 on 2022-04-09 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PR', 'processing'), ('ER', 'error'), ('CO', 'complete')], default='PR', max_length=2)),
                ('message', models.TextField(null=True)),
                ('task_id', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('data', models.FileField(null=True, upload_to='collections')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lexicon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TopicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PR', 'processing'), ('ER', 'error'), ('CO', 'complete')], default='PR', max_length=2)),
                ('message', models.TextField(null=True)),
                ('task_id', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('topic_count', models.IntegerField(default=50)),
                ('max_context_size', models.IntegerField(default=3000)),
                ('lowercase', models.BooleanField(default=True)),
                ('split_pattern', models.CharField(default='\\s+', max_length=200)),
                ('token_pattern_in', models.CharField(default='(\\S+)', max_length=200)),
                ('token_pattern_out', models.CharField(default='\\1', max_length=200)),
                ('data', models.FileField(null=True, upload_to='models')),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='topic_modeling.collection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PR', 'processing'), ('ER', 'error'), ('CO', 'complete')], default='PR', max_length=2)),
                ('message', models.TextField(null=True)),
                ('task_id', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='topic_modeling.collection')),
                ('lexicon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='topic_modeling.lexicon')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='topic_modeling.topicmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('author', models.TextField(null=True)),
                ('text', models.TextField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='topic_modeling.collection')),
            ],
        ),
    ]
