# Generated by Django 4.0 on 2021-12-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='data',
            field=models.FileField(null=True, upload_to='collections'),
        ),
    ]
