# Generated by Django 3.1.14 on 2022-05-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lexicon',
            name='lexicon',
            field=models.JSONField(null=True),
        ),
    ]
