# Generated by Django 4.0 on 2021-12-28 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '0002_alter_user_managers_remove_user_username_and_more'),
        ('topic_modeling', '0002_alter_collection_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmodel',
            name='data',
            field=models.FileField(null=True, upload_to='models'),
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='lowercase',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='max_context_size',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='split_pattern',
            field=models.CharField(default='\\s+', max_length=200),
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='token_pattern_in',
            field=models.CharField(default='(\\S+)', max_length=200),
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='token_pattern_out',
            field=models.CharField(default='\\1', max_length=200),
        ),
        migrations.AlterField(
            model_name='collection',
            name='state',
            field=models.CharField(choices=[('PR', 'processing'), ('ER', 'error'), ('CO', 'complete')], default='PR', max_length=2),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='state',
            field=models.CharField(choices=[('PR', 'processing'), ('ER', 'error'), ('CO', 'complete')], default='PR', max_length=2),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='topic_count',
            field=models.IntegerField(default=50),
        ),
        migrations.CreateModel(
            name='Lexicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(null=True)),
                ('public', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('data', models.JSONField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cdh.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
