# Generated by Django 4.0 on 2021-12-29 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '0002_alter_user_managers_remove_user_username_and_more'),
        ('topic_modeling', '0004_rename_content_document_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicmodel',
            name='max_context_size',
            field=models.IntegerField(default=3000),
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(null=True)),
                ('state', models.CharField(choices=[('PR', 'processing'), ('ER', 'error'), ('CO', 'complete')], default='PR', max_length=2)),
                ('message', models.TextField(null=True)),
                ('task_id', models.CharField(max_length=200, null=True)),
                ('public', models.BooleanField(default=False)),
                ('data', models.JSONField()),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='topic_modeling.collection')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cdh.user')),
                ('lexicon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='topic_modeling.lexicon')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='topic_modeling.topicmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
