# Generated by Django 3.1.14 on 2022-05-14 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0004_auto_20220514_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicmodel',
            old_name='data',
            new_name='serialized',
        ),
        migrations.DeleteModel(
            name='Output',
        ),
    ]
