# Generated by Django 3.1.14 on 2022-05-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0005_auto_20220514_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicmodel',
            name='serialized',
            field=models.FileField(null=True, upload_to='topic_models/serialized'),
        ),
    ]
