# Generated by Django 4.0.1 on 2022-01-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0005_alter_topicmodel_max_context_size_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lexicon',
            name='data',
        ),
        migrations.RemoveField(
            model_name='output',
            name='data',
        ),
        migrations.AddField(
            model_name='output',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
