# Generated by Django 4.0.2 on 2022-03-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0006_remove_lexicon_data_remove_output_data_output_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lexicon',
            name='lexicon',
            field=models.JSONField(null=True),
        ),
    ]
