# Generated by Django 3.1.14 on 2022-05-14 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0006_auto_20220514_1430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
