# Generated by Django 3.1.14 on 2022-05-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0007_delete_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lexicon',
            old_name='lexicon',
            new_name='lexical_sets',
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='max_context_size',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='serialized',
            field=models.FileField(null=True, upload_to='topic_modeling/serialized'),
        ),
    ]
