# Generated by Django 4.0.2 on 2022-03-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0007_lexicon_lexicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='data',
            field=models.FileField(null=True, upload_to='outputs'),
        ),
    ]
