# Generated by Django 3.1.14 on 2022-05-15 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0008_auto_20220515_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PR', 'processing'), ('ER', 'error'), ('CO', 'complete')], default='PR', max_length=2)),
                ('message', models.TextField(null=True)),
                ('task_id', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('results', models.JSONField(null=True)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='topic_modeling.collection')),
                ('lexicon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='topic_modeling.lexicon')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='topic_modeling.topicmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
