# Generated by Django 3.1.14 on 2022-05-15 17:05

from django.db import migrations, models
import topic_modeling.models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0009_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='state',
            field=models.CharField(choices=[('PR', 'processing'), ('ER', 'error'), ('CO', 'complete')], default='PR', max_length=2),
        ),
        migrations.AddField(
            model_name='collection',
            name='task_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='iterations',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='passes',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='random_seed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lexicon',
            name='lexical_sets',
            field=models.JSONField(),
        ),
    ]
