# Generated by Django 3.1.14 on 2022-05-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0010_auto_20220515_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmodel',
            name='alpha',
            field=models.CharField(choices=[('symmetric', 'Symmetric'), ('asymmetric', 'Asymmetric')], default='symmetric', max_length=20),
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='chunk_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='eta',
            field=models.CharField(choices=[('symmetric', 'Symmetric'), ('asymmetric', 'Asymmetric')], default='symmetric', max_length=20),
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='update_every',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='passes',
            field=models.IntegerField(null=True),
        ),
    ]
