# Generated by Django 3.1.14 on 2022-05-15 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0012_auto_20220515_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='data',
            new_name='disk_serialized',
        ),
        migrations.RenameField(
            model_name='topicmodel',
            old_name='serialized',
            new_name='disk_serialized',
        ),
    ]
