# Generated by Django 3.1.14 on 2022-05-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0013_auto_20220515_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='db_serialized',
        ),
        migrations.RemoveField(
            model_name='topicmodel',
            name='db_serialized',
        ),
        migrations.AlterField(
            model_name='collection',
            name='disk_serialized',
            field=models.FileField(null=True, upload_to='shared/topic_modeling/collections'),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='disk_serialized',
            field=models.FileField(null=True, upload_to='shared/topic_modeling/serialized'),
        ),
    ]
