# Generated by Django 3.1.14 on 2022-05-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0014_auto_20220515_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='disk_serialized_processed',
            field=models.FileField(null=True, upload_to='shared/topic_modeling/processed_collections'),
        ),
    ]
