# Generated by Django 3.1.14 on 2022-05-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0015_collection_disk_serialized_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicmodel',
            name='chunk_size',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='disk_serialized',
            field=models.FileField(null=True, upload_to='shared/topic_modeling/models'),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='iterations',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='passes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='update_every',
            field=models.IntegerField(default=1),
        ),
    ]
