# Generated by Django 3.1.14 on 2022-05-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0016_auto_20220515_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmodel',
            name='disk_serialized_dict',
            field=models.FileField(null=True, upload_to='shared/topic_modeling/models'),
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='disk_serialized_param',
            field=models.FileField(null=True, upload_to='shared/topic_modeling/models'),
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='disk_serialized_state',
            field=models.FileField(null=True, upload_to='shared/topic_modeling/models'),
        ),
    ]
