# Generated by Django 3.1.14 on 2022-05-15 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0017_auto_20220515_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='lexicon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='topic_modeling.lexicon'),
        ),
        migrations.AlterField(
            model_name='output',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='topic_modeling.topicmodel'),
        ),
    ]
