# Generated by Django 3.1.14 on 2022-05-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0018_auto_20220515_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='disk_serialized',
            field=models.FileField(null=True, upload_to='shared/topic_modeling/outputs'),
        ),
    ]
