# Generated by Django 4.0.4 on 2022-05-21 13:16

from django.db import migrations, models
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0021_auto_20220519_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=markdownfield.models.MarkdownField(blank=True, rendered_field='rendered_descriptoin'),
        ),
        migrations.AddField(
            model_name='collection',
            name='rendered_description',
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
        migrations.AddField(
            model_name='lexicon',
            name='description',
            field=markdownfield.models.MarkdownField(blank=True, rendered_field='rendered_descriptoin'),
        ),
        migrations.AddField(
            model_name='lexicon',
            name='rendered_description',
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='description',
            field=markdownfield.models.MarkdownField(blank=True, rendered_field='rendered_descriptoin'),
        ),
        migrations.AddField(
            model_name='output',
            name='rendered_description',
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='description',
            field=markdownfield.models.MarkdownField(blank=True, rendered_field='rendered_descriptoin'),
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='rendered_description',
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lexicon',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='output',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
