# Generated by Django 4.0.4 on 2022-05-21 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0022_collection_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('content', models.JSONField(default=dict)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic_modeling.collection')),
            ],
        ),
        migrations.CreateModel(
            name='LabeledCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PR', 'processing'), ('ER', 'error'), ('CO', 'complete')], default='PR', max_length=2)),
                ('message', models.TextField(null=True)),
                ('task_id', models.CharField(max_length=200, null=True)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='topic_modeling.collection')),
                ('lexicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topic_modeling.lexicon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabeledDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(default=dict, null=True)),
                ('labeled_collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='topic_modeling.labeledcollection')),
            ],
        ),
        migrations.RemoveField(
            model_name='topicmodel',
            name='minimum_count',
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='maximum_count',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='minimum_occurences',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='iterations',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='max_context_size',
            field=models.IntegerField(default=1000, help_text="Over what maximum distance (in words) should two words be considered 'co-occurring'?"),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='maximum_proportion',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='passes',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='topic_count',
            field=models.IntegerField(default=20),
        ),
        migrations.DeleteModel(
            name='Output',
        ),
        migrations.AddField(
            model_name='labeledcollection',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topic_modeling.topicmodel'),
        ),
    ]
