# Generated by Django 4.0.4 on 2022-05-21 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0024_remove_collection_disk_serialized_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicmodel',
            old_name='minimum_occurences',
            new_name='minimum_occurence',
        ),
        migrations.RemoveField(
            model_name='topicmodel',
            name='disk_serialized',
        ),
        migrations.RemoveField(
            model_name='topicmodel',
            name='disk_serialized_dict',
        ),
        migrations.RemoveField(
            model_name='topicmodel',
            name='disk_serialized_param',
        ),
        migrations.RemoveField(
            model_name='topicmodel',
            name='disk_serialized_state',
        ),
        migrations.RemoveField(
            model_name='topicmodel',
            name='maximum_count',
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='maximum_vocabulary',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='serialized',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='collection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='topic_modeling.collection'),
            preserve_default=False,
        ),
    ]
