# Generated by Django 4.0.4 on 2022-05-21 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0025_rename_minimum_occurences_topicmodel_minimum_occurence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicmodel',
            old_name='minimum_occurence',
            new_name='minimum_occurrence',
        ),
    ]
