# Generated by Django 4.0.4 on 2022-05-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0026_rename_minimum_occurence_topicmodel_minimum_occurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmodel',
            name='maximum_documents',
            field=models.IntegerField(default=20000),
        ),
    ]
