# Generated by Django 4.0.4 on 2022-05-21 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0027_topicmodel_maximum_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeleddocument',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='topic_modeling.document'),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='maximum_documents',
            field=models.IntegerField(default=1000),
        ),
    ]
