# Generated by Django 4.0.4 on 2022-05-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0028_labeleddocument_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeledcollection',
            name='name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
