# Generated by Django 4.0.4 on 2022-05-23 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0029_labeledcollection_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='content',
        ),
        migrations.RemoveField(
            model_name='labeleddocument',
            name='content',
        ),
    ]
