# Generated by Django 4.0.4 on 2022-05-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0032_document_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='content',
        ),
        migrations.AddField(
            model_name='document',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
