# Generated by Django 4.0.4 on 2022-05-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0035_alter_document_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialEvolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TemporalEvolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='has_geography',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='has_temporality',
            field=models.BooleanField(default=False),
        ),
    ]
