# Generated by Django 4.0.4 on 2022-05-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0039_spatialevolution_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeleddocument',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
