# Generated by Django 4.0.4 on 2022-05-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0040_labeleddocument_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeleddocumentsection',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
