# Generated by Django 4.0.4 on 2022-06-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0041_labeleddocumentsection_metadata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpatialEvolution',
            new_name='SpatialDistribution',
        ),
    ]
