# Generated by Django 4.0.4 on 2022-06-25 14:43

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0042_rename_spatialevolution_spatialdistribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lexicon',
            name='description',
            field=markdownfield.models.MarkdownField(blank=True, rendered_field='rendered_description'),
        ),
    ]
