# Generated by Django 4.0.4 on 2022-06-25 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0043_alter_lexicon_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='rendered_description',
        ),
        migrations.RemoveField(
            model_name='topicmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='topicmodel',
            name='rendered_description',
        ),
    ]
