# Generated by Django 4.0.4 on 2022-06-25 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0044_remove_collection_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lexicon',
            name='description',
        ),
    ]
