# Generated by Django 4.0.4 on 2022-06-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0045_remove_lexicon_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lexicon',
            name='rendered_description',
        ),
    ]
