# Generated by Django 4.0.4 on 2022-06-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0046_remove_lexicon_rendered_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lexicon',
            name='lexical_sets',
            field=models.TextField(),
        ),
    ]
