# Generated by Django 4.0.4 on 2022-07-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0047_alter_lexicon_lexical_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='geographic',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='temporal',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='lexicon',
            name='lexical_sets',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='max_context_size',
            field=models.IntegerField(default=1000),
        ),
    ]
