# Generated by Django 4.0.4 on 2022-07-19 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0048_document_geographic_document_temporal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='geographic',
            new_name='spatial',
        ),
    ]
