# Generated by Django 4.0.4 on 2022-07-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0049_rename_geographic_document_spatial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
