# Generated by Django 4.0.4 on 2022-07-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0050_document_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicmodel',
            name='maximum_documents',
            field=models.IntegerField(default=30000),
        ),
    ]
