# Generated by Django 4.0.4 on 2022-07-21 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0051_alter_topicmodel_maximum_documents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labeleddocument',
            old_name='labeled_collection',
            new_name='labeledcollection',
        ),
        migrations.RenameField(
            model_name='labeleddocumentsection',
            old_name='labeled_document',
            new_name='labeleddocument',
        ),
        migrations.RenameField(
            model_name='spatialdistribution',
            old_name='labeled_collection',
            new_name='labeledcollection',
        ),
        migrations.RenameField(
            model_name='temporalevolution',
            old_name='labeled_collection',
            new_name='labeledcollection',
        ),
    ]
