# Generated by Django 4.0.4 on 2022-07-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0052_rename_labeled_collection_labeleddocument_labeledcollection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='document',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='document',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='document',
            name='year',
        ),
        migrations.AddField(
            model_name='document',
            name='language',
            field=models.CharField(default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='document',
            name='spatial',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='temporal',
            field=models.DateTimeField(null=True),
        ),
    ]
