# Generated by Django 4.0.6 on 2022-07-25 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0055_labeledcollection_maximum_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporalevolution',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='temporalevolution',
            name='labeledcollection',
        ),
        migrations.DeleteModel(
            name='SpatialDistribution',
        ),
        migrations.DeleteModel(
            name='TemporalEvolution',
        ),
    ]
