# Generated by Django 4.0.6 on 2022-07-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0056_remove_temporalevolution_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='document',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='labeledcollection',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='labeleddocument',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='labeleddocumentsection',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lexicon',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lexicon',
            name='lexical_sets',
            field=models.TextField(default='{\n  "positive_words": ["happy", "glad"],\n  "negative_words": ["awful", "sad.*"]\n}'),
        ),
    ]
