# Generated by Django 4.0.6 on 2022-08-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0058_collection_created_at_document_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='Anonymous', max_length=2000),
        ),
        migrations.AddField(
            model_name='labeleddocument',
            name='name',
            field=models.CharField(default='Anonymous', max_length=2000),
        ),
        migrations.AddField(
            model_name='labeleddocumentsection',
            name='name',
            field=models.CharField(default='Anonymous', max_length=2000),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(default='Anonymous', max_length=2000),
        ),
        migrations.AlterField(
            model_name='labeledcollection',
            name='name',
            field=models.CharField(default='Anonymous', max_length=2000),
        ),
        migrations.AlterField(
            model_name='lexicon',
            name='name',
            field=models.CharField(default='Anonymous', max_length=2000),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='name',
            field=models.CharField(default='Anonymous', max_length=2000),
        ),
    ]
