# Generated by Django 4.0.6 on 2022-08-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0059_remove_document_title_document_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=2000, unique=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=2000, unique=False),
        ),
        migrations.AlterField(
            model_name='labeledcollection',
            name='name',
            field=models.CharField(max_length=2000, unique=False),
        ),
        migrations.AlterField(
            model_name='labeleddocument',
            name='name',
            field=models.CharField(max_length=2000, unique=False),
        ),
        migrations.AlterField(
            model_name='labeleddocumentsection',
            name='name',
            field=models.CharField(max_length=2000, unique=False),
        ),
        migrations.AlterField(
            model_name='lexicon',
            name='name',
            field=models.CharField(max_length=2000, unique=False),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='name',
            field=models.CharField(max_length=2000, unique=False),
        ),
    ]
