# Generated by Django 4.0.6 on 2022-08-08 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0061_alter_collection_name_alter_document_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeledcollection',
            name='maximum_documents',
            field=models.IntegerField(default=30000, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
