# Generated by Django 4.0.7 on 2022-08-08 21:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0062_alter_labeledcollection_maximum_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeledcollection',
            name='collection',
            field=models.ForeignKey(help_text='The document collection to label', null=True, on_delete=django.db.models.deletion.CASCADE, to='topic_modeling.collection'),
        ),
        migrations.AlterField(
            model_name='labeledcollection',
            name='lexicon',
            field=models.ForeignKey(blank=True, help_text="The lexicon to apply (mutually exclusive with 'model')", null=True, on_delete=django.db.models.deletion.CASCADE, to='topic_modeling.lexicon'),
        ),
        migrations.AlterField(
            model_name='labeledcollection',
            name='maximum_documents',
            field=models.IntegerField(default=30000, help_text='Randomly choose this number of documents to label (if the collection is larger)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='labeledcollection',
            name='model',
            field=models.ForeignKey(blank=True, help_text="The topic model to apply (mutually exclusive with 'lexicon')", null=True, on_delete=django.db.models.deletion.CASCADE, to='topic_modeling.topicmodel'),
        ),
        migrations.AlterField(
            model_name='lexicon',
            name='lexical_sets',
            field=models.TextField(default='{\n  "positive_words": ["happy", "glad"],\n  "negative_words": ["awful", "sad.*"]\n}', help_text='dsa'),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='collection',
            field=models.ForeignKey(help_text='The document collection to train on', on_delete=django.db.models.deletion.CASCADE, to='topic_modeling.collection'),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='lowercase',
            field=models.BooleanField(default=True, help_text='Whether to convert text to lower-case'),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='max_context_size',
            field=models.IntegerField(default=1000, help_text='If a document has more tokens than this, it will be split up into sub-documents'),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='maximum_documents',
            field=models.IntegerField(default=30000, help_text='Randomly choose this number of documents to train on (if the collection is larger)'),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='maximum_proportion',
            field=models.FloatField(default=0.5, help_text='Ignore words that occur in more than this proportion of documents (often function words and formatting)'),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='maximum_vocabulary',
            field=models.IntegerField(default=5000, help_text='Only consider this number of most-frequent words in the data'),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='minimum_occurrence',
            field=models.IntegerField(default=5, help_text='Ignore words that occur less than this number of times (often misspellings and other noise)'),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='topic_count',
            field=models.IntegerField(default=10, help_text='The number of topics to infer from the data'),
        ),
    ]
