# Generated by Django 4.0.7 on 2022-08-28 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary_sources', '0015_primarysource_message_primarysource_state_and_more'),
        ('topic_modeling', '0063_alter_labeledcollection_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='query',
            field=models.ForeignKey(help_text='A primary source query', null=True, on_delete=django.db.models.deletion.CASCADE, to='primary_sources.query'),
        ),
    ]
