# Generated by Django 4.0.7 on 2022-09-04 19:09

import cdh.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0064_collection_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeleddocument',
            name='material_id',
            field=models.CharField(max_length=1000, null=True),
        ),
        #migrations.AlterField(
        #    model_name='lexicon',
        #    name='lexical_sets',
        #    field=cdh.fields.JsonField(default='{\n  "positive_words": ["happy", "glad"],\n  "negative_words": ["awful", "sad.*"]\n}'),
        #),
        migrations.AlterField(
            model_name='topicmodel',
            name='max_context_size',
            field=models.IntegerField(default=5000, help_text='If a document has more tokens than this, it will be split up into sub-documents'),
        ),
    ]
