# Generated by Django 4.0.7 on 2022-09-14 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary_sources', '0017_alter_query_options_alter_primarysource_created_by_and_more'),
        ('topic_modeling', '0066_alter_collection_created_by_alter_collection_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmodel',
            name='query',
            field=models.ForeignKey(help_text='The primary source query to train on', null=True, on_delete=django.db.models.deletion.CASCADE, to='primary_sources.query'),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='collection',
            field=models.ForeignKey(help_text='The document collection to train on', null=True, on_delete=django.db.models.deletion.CASCADE, to='topic_modeling.collection'),
        ),
    ]
