# Generated by Django 4.0.7 on 2022-09-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0067_topicmodel_query_alter_topicmodel_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='document',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='labeledcollection',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='labeledcollection',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='labeledcollection',
            name='lexicon',
        ),
        migrations.RemoveField(
            model_name='labeledcollection',
            name='model',
        ),
        migrations.RemoveField(
            model_name='labeleddocument',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='labeleddocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='labeleddocument',
            name='labeledcollection',
        ),
        migrations.RemoveField(
            model_name='labeleddocumentsection',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='labeleddocumentsection',
            name='labeleddocument',
        ),
        migrations.RemoveField(
            model_name='topicmodel',
            name='collection',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='LabeledCollection',
        ),
        migrations.DeleteModel(
            name='LabeledDocument',
        ),
        migrations.DeleteModel(
            name='LabeledDocumentSection',
        ),
    ]
