# Generated by Django 3.1.14 on 2022-04-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='active',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='name',
        ),
        migrations.AddField(
            model_name='slidepage',
            name='slug',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='slug',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
