# Generated by Django 3.1.14 on 2022-04-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '0002_auto_20220409_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slidepage',
            name='slug',
        ),
        migrations.AddField(
            model_name='slide',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slidepage',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
