# Generated by Django 3.1.14 on 2022-04-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '0003_auto_20220409_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
