# Generated by Django 3.1.14 on 2022-05-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '0004_slide_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidepage',
            name='additional_link_prompt',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
