# Generated by Django 3.1.14 on 2022-05-09 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '10002_auto_20220508_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='description',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='rendered_description',
            new_name='rendered_article',
        ),
    ]
