# Generated by Django 3.1.14 on 2022-05-09 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '10003_auto_20220508_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='name',
            new_name='title',
        ),
    ]
