# Generated by Django 3.1.14 on 2022-05-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '10000_auto_20220508_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidepage',
            name='additional_link_prompt',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
    ]
