# Generated by Django 3.1.14 on 2022-05-10 17:09

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '10007_remove_slide_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='article',
            field=markdownfield.models.MarkdownField(blank=True, rendered_field='rendered_article'),
        ),
    ]
