# Generated by Django 4.0.7 on 2022-08-31 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cdh', '10017_alter_documentation_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='view_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
