# Generated by Django 4.0.6 on 2022-08-16 17:44

import cdh.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '10014_remove_researchartifact_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchartifact',
            name='description',
            field=cdh.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='article',
            field=cdh.fields.MarkdownField(blank=True, null=True),
        ),
    ]
