# Generated by Django 4.0.4 on 2022-06-25 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '10010_basemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseModel',
        ),
    ]
