# Generated by Django 4.0.6 on 2022-08-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '10011_delete_basemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(default='blah', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slidepage',
            name='name',
            field=models.CharField(default='blah', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
