# Generated by Django 4.0.7 on 2022-08-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '10016_remove_researchartifact_authors_documentation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
