# Generated by Django 4.0.6 on 2022-08-15 21:54

import cdh.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '10013_remove_slide_title_slide_created_at_slide_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchartifact',
            name='active',
        ),
        migrations.RemoveField(
            model_name='researchartifact',
            name='rendered_description',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='active',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='rendered_article',
        ),
        migrations.AlterField(
            model_name='researchartifact',
            name='description',
            field=cdh.fields.MarkdownField(blank=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='article',
            field=cdh.fields.MarkdownField(blank=True),
        ),
        migrations.DeleteModel(
            name='SlidePage',
        ),
    ]
