# Generated by Django 4.0.7 on 2022-08-31 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cdh', '10018_documentation_view_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
