# Generated by Django 4.0.7 on 2022-09-17 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '10025_user_created_at_user_created_by_user_modified_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentation',
            old_name='value',
            new_name='content',
        ),
    ]
