# Generated by Django 4.0.7 on 2022-09-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '10026_rename_value_documentation_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchartifact',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='article',
            field=models.TextField(blank=True, null=True),
        ),
    ]
