# Generated by Django 4.0.7 on 2022-09-13 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '10023_remove_researchartifact_author_freetext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='metadata',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='researchartifact',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='researchartifact',
            name='metadata',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='slide',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slide',
            name='metadata',
            field=models.JSONField(default=dict, editable=False),
        ),
    ]
