# Generated by Django 4.0.7 on 2022-08-31 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '10021_documentation_path_documentation_path_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentation',
            name='path',
        ),
        migrations.RemoveField(
            model_name='documentation',
            name='path_template',
        ),
    ]
