# Generated by Django 4.0.7 on 2022-08-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '10019_alter_documentation_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
