# Generated by Django 4.0.7 on 2022-09-21 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '10027_alter_documentation_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_by',
        ),
    ]
