# Generated by Django 4.0.7 on 2022-09-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '10022_remove_documentation_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchartifact',
            name='author_freetext',
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='address',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='appendix',
            field=models.FileField(null=True, upload_to='research/appendices'),
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='author',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='booktitle',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='chapter',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='document',
            field=models.FileField(null=True, upload_to='research/documents'),
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='doi',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='edition',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='editor',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='howpublished',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='image',
            field=models.ImageField(null=True, upload_to='research/images'),
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='institution',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='journal',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='key',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='month',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='number',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='organization',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='pages',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='publisher',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='school',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='series',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='slides',
            field=models.FileField(null=True, upload_to='research/slides'),
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='type',
            field=models.CharField(choices=[('article', 'Article'), ('book', 'Book'), ('booklet', 'Booklet'), ('conference', 'Conference'), ('inbook', 'Contribution to book'), ('incollection', 'Contribution to collection'), ('inproceedings', 'Contribution to conference or workshop'), ('manual', 'Technical documentation'), ('mastersthesis', 'Masters thesis'), ('misc', 'Miscellaneous'), ('phdthesis', 'PhD thesis'), ('proceedings', 'Conference or workshop proceedings'), ('techreport', 'Technical report'), ('unpublished', 'Unpublished')], default='article', max_length=100),
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='url',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='volume',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='researchartifact',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, upload_to='slides'),
        ),
    ]
