# Generated by Django 4.0.7 on 2022-08-31 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cdh', '10020_alter_documentation_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='path',
            field=models.CharField(editable=False, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='documentation',
            name='path_template',
            field=models.CharField(editable=False, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='content_type',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='view_name',
            field=models.CharField(editable=False, max_length=200, null=True),
        ),
    ]
