# Generated by Django 4.0.7 on 2022-09-21 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '10028_remove_user_created_at_remove_user_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='modified_at',
        ),
    ]
