# Generated by Django 4.0.7 on 2022-09-27 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
        ('cdh', '10034_schedulerule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduleRule',
            new_name='Rule',
        ),
    ]
