# Generated by Django 4.0.7 on 2022-09-23 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '10030_user_created_at_user_created_by_user_modified_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchartifact',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.RenameField(
            model_name='researchartifact',
            old_name='url',
            new_name='biburl',
        ),
    ]
