# Generated by Django 3.1.14 on 2022-05-07 18:31

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '0005_auto_20220501_1449'),
    ]

    operations = [

    ]
