# Generated by Django 4.0.4 on 2022-06-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_sources', '0002_alter_dataset_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('sparql', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
