# Generated by Django 4.0.6 on 2022-08-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_sources', '0008_primarysource_created_at_query_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarysource',
            name='name',
            field=models.CharField(default='Anonymous', max_length=2000),
        ),
        migrations.AlterField(
            model_name='query',
            name='name',
            field=models.CharField(default='Anonymous', max_length=2000),
        ),
    ]
