# Generated by Django 4.0.6 on 2022-08-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_sources', '0009_alter_primarysource_name_alter_query_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarysource',
            name='name',
            field=models.CharField(max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='name',
            field=models.CharField(max_length=2000, unique=True),
        ),
    ]
