# Generated by Django 4.0.6 on 2022-08-16 18:42

import cdh.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primary_sources', '0011_alter_primarysource_name_alter_query_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='sparql',
            field=cdh.fields.SparqlField(),
        ),
    ]
