# Generated by Django 4.0.6 on 2022-08-17 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary_sources', '0013_rename_dataset_query_primary_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='primary_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary_sources.primarysource'),
        ),
    ]
