# Generated by Django 4.0.7 on 2022-09-05 15:01

import cdh.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primary_sources', '0015_primarysource_message_primarysource_state_and_more'),
    ]

    operations = [
        #migrations.AlterField(
        #    model_name='query',
        #    name='sparql',
        #    field=cdh.fields.SparqlField(default='PREFIX cdh: <http://cdh.jhu.edu/materials/>\nPREFIX so: <https://schema.org/>\nPREFIX shacl: <http://www.w3.org/ns/shacl#>\nPREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>\nPREFIX xsd: <http://www.w3.org/2001/XMLSchema#>\nSELECT ?s ?v ?o where { ?s ?v ?o }\n    '),
        #),
    ]
