# Generated by Django 4.0.7 on 2022-10-01 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primary_sources', '0017_alter_query_options_alter_primarysource_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='primary_source',
            new_name='primarysource',
        ),
    ]
