# Generated by Django 4.0.7 on 2022-10-02 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('primary_sources', '0019_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='model_type',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
