# Generated by Django 4.0.7 on 2022-10-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_sources', '0020_annotation_model_type_annotation_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='model_type',
        ),
        migrations.AddField(
            model_name='annotation',
            name='model_class',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
