# Generated by Django 4.0.7 on 2022-10-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_sources', '0021_remove_annotation_model_type_annotation_model_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='app_label',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
