# Generated by Django 4.0.7 on 2022-10-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_sources', '0022_annotation_app_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='object_id',
            field=models.PositiveIntegerField(default=10, editable=False),
            preserve_default=False,
        ),
    ]
