# Generated by Django 4.0.7 on 2022-10-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_sources', '0023_alter_annotation_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='message',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='state',
            field=models.CharField(choices=[('PR', 'processing'), ('ER', 'error'), ('CO', 'complete')], default='PR', editable=False, max_length=2),
        ),
        migrations.AddField(
            model_name='annotation',
            name='task_id',
            field=models.CharField(editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
